---
controller_projects_dev: []
  # - name: controller_configs_dev
  #   description: controller configuration dev only
  #   organization: config_as_code
  #   scm_type: git
  #   scm_url: https://gitlab.consulting.redhat.com/lab-automation/controller_config.git
  #   scm_branch: main
  #   scm_clean: true
  #   scm_update_on_launch: true
  #   scm_credential: gitlab-controller_config
  #   update_project: true
  #   wait: true
...